// flow-typed signature: e7044bff699b071f34ad26fc540cc257
// flow-typed version: <<STUB>>/@turf/along_v^5.1.5/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@turf/along'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@turf/along' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@turf/along/main.es' {
  declare module.exports: any;
}

declare module '@turf/along/main' {
  declare module.exports: any;
}

// Filename aliases
declare module '@turf/along/index' {
  declare module.exports: $Exports<'@turf/along'>;
}
declare module '@turf/along/index.js' {
  declare module.exports: $Exports<'@turf/along'>;
}
declare module '@turf/along/main.es.js' {
  declare module.exports: $Exports<'@turf/along/main.es'>;
}
declare module '@turf/along/main.js' {
  declare module.exports: $Exports<'@turf/along/main'>;
}
