// flow-typed signature: 8892dd3601552e42d4f1ee77e4fb717f
// flow-typed version: <<STUB>>/@turf/helpers_v^6.0.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@turf/helpers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@turf/helpers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@turf/helpers/index' {
  declare module.exports: $Exports<'@turf/helpers'>;
}
declare module '@turf/helpers/index.js' {
  declare module.exports: $Exports<'@turf/helpers'>;
}
