// flow-typed signature: d1935329100260d7b4e77c053ad9d507
// flow-typed version: <<STUB>>/mapbox_v^1.0.0-beta9/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mapbox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mapbox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mapbox/dist/mapbox-sdk' {
  declare module.exports: any;
}

declare module 'mapbox/dist/mapbox-sdk.min' {
  declare module.exports: any;
}

declare module 'mapbox/lib/callbackify' {
  declare module.exports: any;
}

declare module 'mapbox/lib/client' {
  declare module.exports: any;
}

declare module 'mapbox/lib/constants' {
  declare module.exports: any;
}

declare module 'mapbox/lib/encode_overlay' {
  declare module.exports: any;
}

declare module 'mapbox/lib/format_points' {
  declare module.exports: any;
}

declare module 'mapbox/lib/get_user' {
  declare module.exports: any;
}

declare module 'mapbox/lib/invariant_location' {
  declare module.exports: any;
}

declare module 'mapbox/lib/make_service' {
  declare module.exports: any;
}

declare module 'mapbox/lib/mapbox' {
  declare module.exports: any;
}

declare module 'mapbox/lib/paginator' {
  declare module.exports: any;
}

declare module 'mapbox/lib/promise' {
  declare module.exports: any;
}

declare module 'mapbox/lib/services/datasets' {
  declare module.exports: any;
}

declare module 'mapbox/lib/services/directions' {
  declare module.exports: any;
}

declare module 'mapbox/lib/services/geocoding' {
  declare module.exports: any;
}

declare module 'mapbox/lib/services/matching' {
  declare module.exports: any;
}

declare module 'mapbox/lib/services/matrix' {
  declare module.exports: any;
}

declare module 'mapbox/lib/services/static' {
  declare module.exports: any;
}

declare module 'mapbox/lib/services/styles' {
  declare module.exports: any;
}

declare module 'mapbox/lib/services/surface' {
  declare module.exports: any;
}

declare module 'mapbox/lib/services/tilesets' {
  declare module.exports: any;
}

declare module 'mapbox/lib/services/tilestats' {
  declare module.exports: any;
}

declare module 'mapbox/lib/services/tokens' {
  declare module.exports: any;
}

declare module 'mapbox/lib/services/uploads' {
  declare module.exports: any;
}

declare module 'mapbox/lib/standard_response' {
  declare module.exports: any;
}

declare module 'mapbox/vendor/hat' {
  declare module.exports: any;
}

declare module 'mapbox/vendor/invariant' {
  declare module.exports: any;
}

declare module 'mapbox/vendor/polyline' {
  declare module.exports: any;
}

declare module 'mapbox/vendor/xtend' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mapbox/dist/mapbox-sdk.js' {
  declare module.exports: $Exports<'mapbox/dist/mapbox-sdk'>;
}
declare module 'mapbox/dist/mapbox-sdk.min.js' {
  declare module.exports: $Exports<'mapbox/dist/mapbox-sdk.min'>;
}
declare module 'mapbox/lib/callbackify.js' {
  declare module.exports: $Exports<'mapbox/lib/callbackify'>;
}
declare module 'mapbox/lib/client.js' {
  declare module.exports: $Exports<'mapbox/lib/client'>;
}
declare module 'mapbox/lib/constants.js' {
  declare module.exports: $Exports<'mapbox/lib/constants'>;
}
declare module 'mapbox/lib/encode_overlay.js' {
  declare module.exports: $Exports<'mapbox/lib/encode_overlay'>;
}
declare module 'mapbox/lib/format_points.js' {
  declare module.exports: $Exports<'mapbox/lib/format_points'>;
}
declare module 'mapbox/lib/get_user.js' {
  declare module.exports: $Exports<'mapbox/lib/get_user'>;
}
declare module 'mapbox/lib/invariant_location.js' {
  declare module.exports: $Exports<'mapbox/lib/invariant_location'>;
}
declare module 'mapbox/lib/make_service.js' {
  declare module.exports: $Exports<'mapbox/lib/make_service'>;
}
declare module 'mapbox/lib/mapbox.js' {
  declare module.exports: $Exports<'mapbox/lib/mapbox'>;
}
declare module 'mapbox/lib/paginator.js' {
  declare module.exports: $Exports<'mapbox/lib/paginator'>;
}
declare module 'mapbox/lib/promise.js' {
  declare module.exports: $Exports<'mapbox/lib/promise'>;
}
declare module 'mapbox/lib/services/datasets.js' {
  declare module.exports: $Exports<'mapbox/lib/services/datasets'>;
}
declare module 'mapbox/lib/services/directions.js' {
  declare module.exports: $Exports<'mapbox/lib/services/directions'>;
}
declare module 'mapbox/lib/services/geocoding.js' {
  declare module.exports: $Exports<'mapbox/lib/services/geocoding'>;
}
declare module 'mapbox/lib/services/matching.js' {
  declare module.exports: $Exports<'mapbox/lib/services/matching'>;
}
declare module 'mapbox/lib/services/matrix.js' {
  declare module.exports: $Exports<'mapbox/lib/services/matrix'>;
}
declare module 'mapbox/lib/services/static.js' {
  declare module.exports: $Exports<'mapbox/lib/services/static'>;
}
declare module 'mapbox/lib/services/styles.js' {
  declare module.exports: $Exports<'mapbox/lib/services/styles'>;
}
declare module 'mapbox/lib/services/surface.js' {
  declare module.exports: $Exports<'mapbox/lib/services/surface'>;
}
declare module 'mapbox/lib/services/tilesets.js' {
  declare module.exports: $Exports<'mapbox/lib/services/tilesets'>;
}
declare module 'mapbox/lib/services/tilestats.js' {
  declare module.exports: $Exports<'mapbox/lib/services/tilestats'>;
}
declare module 'mapbox/lib/services/tokens.js' {
  declare module.exports: $Exports<'mapbox/lib/services/tokens'>;
}
declare module 'mapbox/lib/services/uploads.js' {
  declare module.exports: $Exports<'mapbox/lib/services/uploads'>;
}
declare module 'mapbox/lib/standard_response.js' {
  declare module.exports: $Exports<'mapbox/lib/standard_response'>;
}
declare module 'mapbox/vendor/hat.js' {
  declare module.exports: $Exports<'mapbox/vendor/hat'>;
}
declare module 'mapbox/vendor/invariant.js' {
  declare module.exports: $Exports<'mapbox/vendor/invariant'>;
}
declare module 'mapbox/vendor/polyline.js' {
  declare module.exports: $Exports<'mapbox/vendor/polyline'>;
}
declare module 'mapbox/vendor/xtend.js' {
  declare module.exports: $Exports<'mapbox/vendor/xtend'>;
}
