// flow-typed signature: c195ae1318a0a6d564ea5551347c5ae4
// flow-typed version: <<STUB>>/react-navigator_v^0.0.0-0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-navigator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-navigator' {
  declare module.exports: any;
}
