// flow-typed signature: e6b3492256a0808cf77b707c59b14037
// flow-typed version: <<STUB>>/react-native-parallax-scroll-view_v^0.20.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-parallax-scroll-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-parallax-scroll-view' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-parallax-scroll-view/src/index' {
  declare module.exports: any;
}

declare module 'react-native-parallax-scroll-view/src/styles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-parallax-scroll-view/src/index.js' {
  declare module.exports: $Exports<'react-native-parallax-scroll-view/src/index'>;
}
declare module 'react-native-parallax-scroll-view/src/styles.js' {
  declare module.exports: $Exports<'react-native-parallax-scroll-view/src/styles'>;
}
