// flow-typed signature: 1a8880e051f3897d8a229f0dbb96c82b
// flow-typed version: <<STUB>>/turf_v^3.0.14/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'turf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'turf' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'turf/turf' {
  declare module.exports: any;
}

declare module 'turf/turf.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'turf/index' {
  declare module.exports: $Exports<'turf'>;
}
declare module 'turf/index.js' {
  declare module.exports: $Exports<'turf'>;
}
declare module 'turf/turf.js' {
  declare module.exports: $Exports<'turf/turf'>;
}
declare module 'turf/turf.min.js' {
  declare module.exports: $Exports<'turf/turf.min'>;
}
