# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'GuiaAnimus' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!



 # React Native

  # Pods for GuiaAnimus
  pod 'Firebase/Messaging'


 
  pod 'react-native-mapbox-gl', :path => '../node_modules/@mapbox/react-native-mapbox-gl'

  pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'

end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
