// flow-typed signature: 815c22a285567f80b430190cf17f31f6
// flow-typed version: <<STUB>>/@merryjs/photo-viewer_v^2.1.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@merryjs/photo-viewer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@merryjs/photo-viewer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@merryjs/photo-viewer/index' {
  declare module.exports: $Exports<'@merryjs/photo-viewer'>;
}
declare module '@merryjs/photo-viewer/index.js' {
  declare module.exports: $Exports<'@merryjs/photo-viewer'>;
}
